spring.application.name=backend
server.port=8080

# Aiven MySQL Connection
spring.datasource.url=jdbc:mysql://mysql-d99ce19-sandspacedevteam-1070.e.aivencloud.com:13951/defaultdb?useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=REPLACE_WITH_YOUR_PASSWORD

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
